CU-2q6vya Footer
RadishLab/clf001 pull request #28
Opened 2020-12-03 20:06 UTC by hernangalvan

Include settings, components, layout and styles for footer.

![image](https://user-images.githubusercontent.com/7491955/101081999-93b77e80-3589-11eb-9236-25f88848d99d.png)

![image](https://user-images.githubusercontent.com/7491955/101082117-b9448800-3589-11eb-8790-e04e2176cc72.png)

![image](https://user-images.githubusercontent.com/7491955/101082165-c9f4fe00-3589-11eb-9a79-e6cdab62711e.png)

2020-12-03 20:06 UTC, alesub commented
Task linked: [CU-2q6vya Footer](https://app.clickup.com/t/2q6vya)

2020-12-04 02:46 UTC, alesub requested changes

2020-12-04 02:46 UTC, alesub commented on web/wp-content/themes/clf001/app/fields/partials/footer_options.php
> +        ->addTextarea('text', ['label' => 'Text', 'new_lines' => 'br'])
It's better to change this kind of field to the wysiwyg one, with "toolbar" set to "basic" and "media_upload" to "false". That way, the user will be able to enter simple paragraphs, but will also be able to set words to bold, insert links and line breaks correctly. This applies to all the textarea fields with "new_lines" set to "br".

2020-12-04 15:13 UTC, hernangalvan commented on web/wp-content/themes/clf001/app/fields/partials/footer_options.php
> +        ->addTextarea('text', ['label' => 'Text', 'new_lines' => 'br'])
Changed textarea for basic wysiwyg

2020-12-04 15:43 UTC, alesub approved these changes

2020-12-04 15:43 UTC, merged